project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - "images/"

website:
  title: "Tsering Sherpa"
  description: "PhD Student at the University of Washington"
  image: "images/profile.jpeg"
  favicon: "images/logo.png"
  twitter-card: true
  open-graph: true
  site-url: https://tseringlsherpa.github.io
  navbar:
    logo: "images/logo.png"
    logo-alt: "Logo"
    collapse: true
    background: light
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: "CV"
        href: files/cv.pdf
      - text: "Research"
        href: res.qmd
      - text: "Dawgs"
        href: dogs.qmd
      - text: "Teaching & Resources"
        href: teaching.qmd
        menu:
          - text: "QSCI 381"
            href: qsci381-resources.qmd
          - text: "Sources I Like"
            href: tools.qmd
          
    right:
    - icon: github
      href: https://github.com/tseringlsherpa
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/tseringlsherpa/
      target: _blank
    - text: ORCID
      href: https://orcid.org/0009-0000-5484-803X
      target: _blank
  page-footer:
    center: 
      - text: "tsherp@uw.edu"
        icon: envelope
        href: "mailto:tsherp@uw.edu"
      - text: "319C Savery Hall, University of Washington, Seattle, WA"
          
format:
  html:
    css: styles.css
    anchor-sections: false
    theme: 
      dark: darkly
      light: flatly
    toc: true
