project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - "images/"

website:
  title: "Tsering Sherpa"
  description: "PhD Student at the University of Washington"
  image: "images/profile.jpeg"
  favicon: "images/logo.png"
  twitter-card: true
  open-graph: true
  site-url: https://tseringlsherpa.github.io
  navbar:
    logo: "images/logo.png"
    logo-alt: "Logo"
    collapse: true
    background: light
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: "CV"
        href: files/cv.pdf
      - text: Research
      - href: research.qmd
            
      - text: "Teaching"
        href: teaching.qmd
      - text: Resources 
        menu:
          - text: "QSCI 381"
            href: qsci381-resources.qmd
          - text: "Additional Tools"
            href: tools.qmd
      - text: "More"
        menu:
          - text: "Dawgs"
            href: dogs.qmd
          - text: Blog
          - href: posts/index.qmd
    right:
      - icon: github
        href: https://github.com/tseringlsherpa
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/tseringlsherpa/
        target: _blank
      - icon: ORCID
      - href: https://orcid.org/0009-0000-5484-803X
      - target: _blank
  page-footer:
    center: 
      - text: "tsherp@uw.edu"
        icon: envelope
        href: "mailto:tsherp@uw.edu"
      - text: "319C Savery Hall, University of Washington, Seattle, WA"
          
format:
  html:
    css: styles.css
    anchor-sections: false
    theme: 
      dark: darkly
      light: flatly
    toc: true

