project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - "images/"

website:
  title: "Tsering Sherpa"
  description: "PhD Student at the University of Washington"
  image: "images/profile.jpeg"
  favicon: "images/logo.png"
  twitter-card: true
  open-graph: true
  site-url: https://tseringlsherpa.github.io

  navbar:
    logo: "images/logo.png"
    logo-alt: "Logo"
    logo-href: https://econ.washington.edu/people/tsering-sherpa
    collapse: true
    background: light
    search: true

    left:
      - text: Home
        href: index.qmd
      - text: "CV"
        href: files/cv.pdf
      - text: "Research"
        href: res.qmd
      - text: "Teaching"
        menu:
          - text: "Experience"
            href: teaching.qmd
          - text: "QSCI 381"
            href: qsci381-resources.qmd
          - text: "ECON 201"
            href: econ201.qmd
          - text: "ENGL 299"
            href: engl299.qmd
      - text: "Other"
        menu:
          - text: "Ruminating Factors"
            href: blog/blog.qmd
          - text: "Suggested Sources"
            href: tools.qmd
          - text: "Dawgs"
            href: dogs.qmd
    right:
    - icon: github
      href: https://github.com/tseringlsherpa
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/tseringlsherpa/
      target: _blank

  page-footer:
    center: 
      - icon: envelope 
        text: "tsherp@uw.edu" 
        href: "mailto:tsherp@uw.edu"
      - text: "319C Savery Hall, University of Washington, Seattle, WA"

format:
  html:
    css: styles.css
    anchor-sections: false
    theme:
      dark: darkly
      light: flatly
    toc: true
